/* ─── DEFUSE.EXE — Game Constants ─── */

export const TICK_RATE = 20;                    // ticks per second
export const TICK_MS = 1000 / TICK_RATE;        // 50ms
export const GAME_DURATION_MS = 20 * 60 * 1000; // 20 minutes
export const ARENA_W = 4000;
export const ARENA_H = 4000;
export const SPAWN_MARGIN = 150;                // enemies spawn this far outside arena edge
export const PLAYER_RADIUS = 16;
export const PICKUP_BASE_RANGE = 60;
export const BASE_XP_TO_LEVEL = 20;
export const XP_GROWTH = 1.18;                  // each level needs 18% more
export const BOMB_ZONE_RADIUS = 100;
export const BOMB_ZONE_BASE_DURATION_MS = 30000;
export const BOMB_ZONE_BASE_SPEED = 0.35;       // progress/tick solo (~14s to fill solo)
export const BOMB_ZONE_MULTI_BONUS = 1.8;       // multiplier per extra player
export const BOMB_ZONE_XP_REWARD_BASE = 60;
export const BOMB_ZONE_SPAWN_INTERVAL_MS = 90000;
export const WAVE_DURATION_MS = 60000;           // 1 minute per wave
export const ELITE_HP_MULT = 3;
export const ELITE_DMG_MULT = 1.5;
export const ELITE_SIZE_MULT = 1.5;
export const ELITE_XP_MULT = 5;
export const MINIBOSS_HP_MULT = 15;
export const MINIBOSS_DMG_MULT = 3;
export const MINIBOSS_SIZE_MULT = 2.5;
export const MINIBOSS_XP_MULT = 25;
export const BOSS_HP_MULT = 80;
export const BOSS_DMG_MULT = 4;
export const BOSS_SIZE_MULT = 4;
export const BOSS_XP_MULT = 100;
export const MAX_WEAPONS = 4;
export const MAX_TOKENS = 4;
export const WEAPON_MAX_LEVEL = 30;
export const WEAPON_ASCEND_LEVEL = 10;
export const WEAPON_TRANSCEND_LEVEL = 30;
export const LEVEL_UP_CHOICES = 4;
export const ENEMY_SPAWN_INTERVAL_MS = 2000;  // spawn enemies every 2s
export const MINIBOSS_SPAWN_TIME_MS = 120000; // first miniboss at 2min
export const MINIBOSS_REPEAT_MS = 90000;      // then every 90s
export const BOSS_SPAWN_TIME_MS = 300000;     // first boss at 5min
export const BOSS_REPEAT_MS = 180000;         // then every 3min
export const CRIT_MULTIPLIER = 2;
export const RESPAWN_DELAY_MS = 5000;
export const INVULN_AFTER_HIT_MS = 500;
export const POST_BOSS_WAVE_INTERVAL = 5;       // boss every N waves after 20
export const DAMAGE_NUMBER_LIFETIME = 800;
export const MAX_ENEMIES = 400;
export const MAX_PROJECTILES = 500;
export const MAX_XP_GEMS = 400;
export const MAX_BLACKLISTED_WEAPONS = 8;       // can't blacklist everything
export const MAX_BLACKLISTED_TOKENS = 10;

// Breakable objects
export const MAX_BREAKABLES = 60;
export const BREAKABLE_SPAWN_INTERVAL_MS = 12000; // new set spawns every 12s
export const BREAKABLE_SPAWN_COUNT = 5;           // how many spawn per interval
export const BREAKABLE_HP_CRATE = 15;
export const BREAKABLE_HP_BARREL = 10;
export const BREAKABLE_HP_CRYSTAL = 25;
export const PICKUP_LIFETIME_MS = 15000;
export const PICKUP_COLLECT_RANGE = 40;
